/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
/**
 *
 * @author sidhi
 */
public class AddFlight extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddFlight.class.getName());

    /**
     * Creates new form AddFlight
     */
    public AddFlight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFlightName = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtDepartureDateTime = new javax.swing.JTextField();
        txtArrivalDateTime = new javax.swing.JTextField();
        txtBusPrice = new javax.swing.JTextField();
        txtBusSeats = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEcoPrice = new javax.swing.JTextField();
        txtEcoSeats = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ADD FLIGHT");

        jLabel2.setText("Flight Name");

        jLabel3.setText("Source");

        jLabel4.setText("Destination");

        jLabel5.setText("Departure Date-Time");

        jLabel6.setText("Arrival Date-Time");

        jLabel9.setText("Business Price");

        jLabel10.setText("Business Seats");

        txtSource.addActionListener(this::txtSourceActionPerformed);

        txtDepartureDateTime.addActionListener(this::txtDepartureDateTimeActionPerformed);

        txtBusPrice.addActionListener(this::txtBusPriceActionPerformed);

        txtBusSeats.addActionListener(this::txtBusSeatsActionPerformed);

        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Add Flight");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel11.setText("Economy Price");

        jLabel12.setText("Economy Seats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEcoSeats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(txtEcoPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBusSeats, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBusPrice, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFlightName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(txtSource, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDestination)
                                .addComponent(txtDepartureDateTime)
                                .addComponent(txtArrivalDateTime)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDepartureDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtArrivalDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBusPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtBusSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEcoPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEcoSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtBusPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusPriceActionPerformed

    private void txtBusSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusSeatsActionPerformed

    private void txtSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSourceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String flightName = txtFlightName.getText().trim();
String source = txtSource.getText().trim();
String destination = txtDestination.getText().trim();
String departureDT = txtDepartureDateTime.getText().trim();
String arrivalDT = txtArrivalDateTime.getText().trim();
String busPrice = txtBusPrice.getText().trim();
String busSeats = txtBusSeats.getText().trim();
String ecoPrice = txtEcoPrice.getText().trim();
String ecoSeats = txtEcoSeats.getText().trim();

if (flightName.isEmpty() || source.isEmpty() || destination.isEmpty() ||
    departureDT.isEmpty() || arrivalDT.isEmpty() ||
    busPrice.isEmpty() || busSeats.isEmpty() ||
    ecoPrice.isEmpty() || ecoSeats.isEmpty()) {

    JOptionPane.showMessageDialog(this, "Please fill all required fields");
    return;
}

if (departureDT.equals("yyyy-MM-dd HH:mm:ss") ||
    arrivalDT.equals("yyyy-MM-dd HH:mm:ss")) {

    JOptionPane.showMessageDialog(this, "Please enter valid datetime");
    return;
}

try {
    Integer.parseInt(busPrice);
    Integer.parseInt(busSeats);
    Integer.parseInt(ecoPrice);
    Integer.parseInt(ecoSeats);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this,
        "Prices and seats must be numbers");
    return;
}

SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
sdf.setLenient(false);

try {
    sdf.parse(departureDT);
    sdf.parse(arrivalDT);
} catch (Exception e) {
    JOptionPane.showMessageDialog(this,
        "Use format: yyyy-MM-dd HH:mm:ss");
    return;
}

java.sql.Timestamp depTimestamp =
        java.sql.Timestamp.valueOf(departureDT);

java.sql.Timestamp arrTimestamp =
        java.sql.Timestamp.valueOf(arrivalDT);

if (arrTimestamp.before(depTimestamp)) {
    JOptionPane.showMessageDialog(this,
        "Arrival must be after departure");
    return;
}

try {
    Class.forName("oracle.jdbc.OracleDriver");

    Connection con = DriverManager.getConnection(
            "jdbc:oracle:thin:@//localhost:1522/XEPDB1",
            "system",
            "oracle"
    );

    String sql = "INSERT INTO flight " +
"(flight_name, source, destination, departure_datetime, arrival_datetime, " +
"business_price, business_seats, economy_price, economy_seats) " +
"VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, flightName);
    pst.setString(2, source);
    pst.setString(3, destination);
    pst.setTimestamp(4, depTimestamp);
    pst.setTimestamp(5, arrTimestamp);
    pst.setInt(6, Integer.parseInt(busPrice));
    pst.setInt(7, Integer.parseInt(busSeats));
    pst.setInt(8, Integer.parseInt(ecoPrice));
    pst.setInt(9, Integer.parseInt(ecoSeats));

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this,
        "Flight Added Successfully");
    pst.close();
    con.close();

    txtFlightName.setText("");
    txtSource.setText("");
    txtDestination.setText("");
    txtDepartureDateTime.setText("");
    txtArrivalDateTime.setText("");
    txtEcoPrice.setText("");
    txtBusPrice.setText("");
    txtEcoSeats.setText("");
    txtBusSeats.setText("");

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDepartureDateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartureDateTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartureDateTimeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         txtDepartureDateTime.setText("yyyy-MM-dd HH:mm:ss");

    txtDepartureDateTime.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtDepartureDateTime.getText().equals("yyyy-MM-dd HH:mm:ss")) {
                txtDepartureDateTime.setText("");
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtDepartureDateTime.getText().isEmpty()) {
                txtDepartureDateTime.setText("yyyy-MM-dd HH:mm:ss");
            }
        }
    });

    txtArrivalDateTime.setText("yyyy-MM-dd HH:mm:ss");

    txtArrivalDateTime.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtArrivalDateTime.getText().equals("yyyy-MM-dd HH:mm:ss")) {
                txtArrivalDateTime.setText("");
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtArrivalDateTime.getText().isEmpty()) {
                txtArrivalDateTime.setText("yyyy-MM-dd HH:mm:ss");
            }
        }
    });
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddFlight().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtArrivalDateTime;
    private javax.swing.JTextField txtBusPrice;
    private javax.swing.JTextField txtBusSeats;
    private javax.swing.JTextField txtDepartureDateTime;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtEcoPrice;
    private javax.swing.JTextField txtEcoSeats;
    private javax.swing.JTextField txtFlightName;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
