/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author sidhi
 */
public class AdminViewBookings extends javax.swing.JFrame {
    private JTable tblBookings; 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminViewBookings.class.getName());

    /**
     * Creates new form AdminViewBookings
     */
    private void loadBookings() {
    try {
        Class.forName("oracle.jdbc.OracleDriver");
        Connection con = DriverManager.getConnection(
            "jdbc:oracle:thin:@//localhost:1522/XEPDB1", "system", "oracle");

        String sql = "SELECT b.booking_id, f.flight_name, f.source, f.destination, " +
                     "b.class_type, b.seats, b.total_price, b.booking_date, p.name AS passenger_name " +
                     "FROM booking b " +
                     "JOIN flight f ON b.flight_id = f.flight_id " +
                     "JOIN passenger p ON b.passenger_id = p.passenger_id " +
                     "ORDER BY b.booking_date DESC";

        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        // Table model
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Booking ID", "Passenger", "Flight", "Source", "Destination",
                         "Class", "Seats", "Total", "Date"}, 0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("booking_id"),
                rs.getString("passenger_name"),
                rs.getString("flight_name"),
                rs.getString("source"),
                rs.getString("destination"),
                rs.getString("class_type"),
                rs.getInt("seats"),
                rs.getDouble("total_price"),
                rs.getTimestamp("booking_date")
            });
        }

        tblBookings.setModel(model);

        rs.close();
        pst.close();
        con.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading bookings: " + e.getMessage());
    }
}
    public AdminViewBookings() {
    initComponents();
    loadBookings();  // load data when frame opens
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminViewBookings().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
