/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author sidhi
 */
public class BookTicket extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookTicket.class.getName());

    /**
     * Creates new form BookTicket
     */
    private int flight_id;
private String flight_name, source, destination, datetime;
private int availableEconomy, availableBusiness;
private double economy_price, business_price;
private void updatePrice() {
    double price = rbtnEconomy.isSelected() ? economy_price : business_price;
    int seats = (Integer) spinnerSeats.getValue();

    // Update spinner max according to selected seat type
    if (rbtnEconomy.isSelected()) {
        ((javax.swing.SpinnerNumberModel) spinnerSeats.getModel()).setMaximum(availableEconomy);
    } else {
        ((javax.swing.SpinnerNumberModel) spinnerSeats.getModel()).setMaximum(availableBusiness);
    }

    // Update price label
    lblPrice.setText(String.valueOf(price));

    // Update total
    lblTotal.setText(String.valueOf(price * seats));
}

    public BookTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblFlightName = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbtnEconomy = new javax.swing.JRadioButton();
        rbtnBusiness = new javax.swing.JRadioButton();
        spinnerSeats = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("BOOK TICKET");

        lblFlightName.setText("Flight Name");

        lblSource.setText("Source");

        lblDestination.setText("Destination");

        lblDateTime.setText("Date and Time");

        jLabel6.setText("Seat Type");

        buttonGroup1.add(rbtnEconomy);
        rbtnEconomy.setText("Economy");
        rbtnEconomy.addActionListener(this::rbtnEconomyActionPerformed);

        buttonGroup1.add(rbtnBusiness);
        rbtnBusiness.setText("Business");

        jLabel8.setText("Seat no");

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setText("Confirm Booking");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        lblPrice.setText("Price");

        jLabel2.setText("Total Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDateTime)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(rbtnBusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblFlightName, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(lblSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnEconomy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(lblFlightName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSource)
                .addGap(18, 18, 18)
                .addComponent(lblDestination)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDateTime)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtnBusiness))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnEconomy)
                .addGap(1, 1, 1)
                .addComponent(lblPrice)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public BookTicket(int flight_id, String flight_name, String source, String destination, String datetime,
                  int availableBusiness, int availableEconomy, double business_price, double economy_price) {

    initComponents(); // important: initializes the Swing components

    // store in class variables
    this.flight_id = flight_id;
    this.flight_name = flight_name;
    this.source = source;
    this.destination = destination;
    this.datetime = datetime;
    this.availableBusiness = availableBusiness;
    this.availableEconomy = availableEconomy;
    this.business_price = business_price;
    this.economy_price = economy_price;
System.out.println("DEBUG: " + flight_name + ", " + source + ", " + destination + ", " + datetime);
    displayFlightDetails();
}
private void displayFlightDetails() {
    // Flight info
    lblFlightName.setText("Flight Name: " + flight_name);
    lblSource.setText("Source: " + source);
    lblDestination.setText("Destination: " + destination);
    lblDateTime.setText("DateTime: " + datetime);

    // Default seat selection: Economy
    rbtnEconomy.setSelected(true);

    // Price label
    lblPrice.setText(String.valueOf(economy_price));

    // Spinner for seats
    spinnerSeats.setModel(new javax.swing.SpinnerNumberModel(1, 1, availableEconomy, 1));

    // Total
    lblTotal.setText(String.valueOf(economy_price));

    // Add listeners for seat type selection
    rbtnEconomy.addActionListener(e -> updatePrice());
    rbtnBusiness.addActionListener(e -> updatePrice());

    // Add listener for spinner changes
    spinnerSeats.addChangeListener(e -> updatePrice());
}
private void confirmBooking() {
    try {
        String seatType = rbtnEconomy.isSelected() ? "Economy" : "Business";

        int seats = (Integer) spinnerSeats.getValue();

        double pricePerSeat = rbtnEconomy.isSelected() ? economy_price : business_price;
        double totalPrice = pricePerSeat * seats;

        int passengerId = CurrentUser.getPassengerId();

       
        Class.forName("oracle.jdbc.OracleDriver");
        java.sql.Connection con = java.sql.DriverManager.getConnection(
            "jdbc:oracle:thin:@//localhost:1522/XEPDB1", "system", "oracle");
        
        // 1. get next booking id from sequence
Statement seqStmt = con.createStatement();
ResultSet rsSeq = seqStmt.executeQuery("SELECT booking_seq.NEXTVAL FROM dual");
int bookingId = 0;
if (rsSeq.next()) {
    bookingId = rsSeq.getInt(1);
}
rsSeq.close();
seqStmt.close();

// 2. insert using bookingId
String sql = "INSERT INTO booking (booking_id, flight_id, passenger_id, class_type, seats, total_price) "
           + "VALUES (?, ?, ?, ?, ?, ?)";
PreparedStatement pst = con.prepareStatement(sql);
pst.setInt(1, bookingId);       // booking_id from sequence
pst.setInt(2, flight_id);
pst.setInt(3, passengerId);
pst.setString(4, seatType);
pst.setInt(5, seats);
pst.setDouble(6, totalPrice);

int rows = pst.executeUpdate();
pst.close();

    JOptionPane.showMessageDialog(this, "Booking confirmed! Redirecting to payment.");

    // Pass bookingId to PaymentPage
    PaymentPage paymentPage = new PaymentPage(totalPrice, bookingId);
    paymentPage.setVisible(true);
    this.dispose();
}

     catch (Exception ex) {
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new SelectFlight().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbtnEconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEconomyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnEconomyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        confirmBooking();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookTicket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblFlightName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rbtnBusiness;
    private javax.swing.JRadioButton rbtnEconomy;
    private javax.swing.JSpinner spinnerSeats;
    // End of variables declaration//GEN-END:variables
}
