/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sidhi
 */
public class SelectFlight extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SelectFlight.class.getName());

    /**
     * Creates new form BookTicket
     */
    public SelectFlight() {
        initComponents();
    }
void loadFlights() {

    try {
        Class.forName("oracle.jdbc.OracleDriver");

        Connection con = DriverManager.getConnection(
            "jdbc:oracle:thin:@//localhost:1522/XEPDB1",
            "system",
            "oracle"
        );

        String sql = "SELECT flight_id, flight_name, source, destination, " +
                     "departure_datetime, business_seats, business_price, " +
                     "economy_seats , economy_price" +
                     " FROM flight ";

        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model =
            (DefaultTableModel) tblFlights.getModel();

        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("flight_id"),
                rs.getString("flight_name"),
                rs.getString("source"),
                rs.getString("destination"),
                rs.getTimestamp("departure_datetime"),
                rs.getInt("business_seats"),
                rs.getInt("economy_seats")
            });
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlights = new javax.swing.JTable();
        btnBookTicket = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("BOOK TICKET");

        tblFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight ID", "Name", "Source", "Destination", "DateTime", "Business Seats", "Economy Seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFlights);

        btnBookTicket.setText("Book Ticket");
        btnBookTicket.addActionListener(this::btnBookTicketActionPerformed);

        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addComponent(btnBookTicket)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookTicket)
                    .addComponent(jButton1))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadFlights();
    }//GEN-LAST:event_formWindowOpened

    private void btnBookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTicketActionPerformed
            int selectedRow = tblFlights.getSelectedRow();

    if(selectedRow == -1){
        JOptionPane.showMessageDialog(this, "Please select a flight to book");
        return;
    }

    // 1️⃣ Get flight info and seats from the table
    int flight_id = (int) tblFlights.getValueAt(selectedRow, 0);
    String flight_name = (String) tblFlights.getValueAt(selectedRow, 1);
    String source = (String) tblFlights.getValueAt(selectedRow, 2);
    String destination = (String) tblFlights.getValueAt(selectedRow, 3);
    String datetime = tblFlights.getValueAt(selectedRow, 4).toString();
    int business_seats = Integer.parseInt(tblFlights.getValueAt(selectedRow, 5).toString());
    int economy_seats = Integer.parseInt(tblFlights.getValueAt(selectedRow, 6).toString());
    

    // 2️⃣ Get prices from the database (this is where you add your code)
    double economy_price = 0, business_price = 0;
    try {
            Class.forName("oracle.jdbc.OracleDriver");
    		Connection con = DriverManager.getConnection(
        	"jdbc:oracle:thin:@//localhost:1522/XEPDB1", "system", "oracle");
        PreparedStatement pst = con.prepareStatement(
            "SELECT economy_price, business_price FROM flight WHERE flight_id=?");
        pst.setInt(1, flight_id);
        ResultSet rs = pst.executeQuery();
        if(rs.next()) {
            economy_price = rs.getDouble("economy_price");
            business_price = rs.getDouble("business_price");
        }
        con.close();
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }

    // 3️⃣ Open BookTicket window with all info
    new BookTicket(flight_id, flight_name, source, destination, datetime,
               business_seats, economy_seats, business_price, economy_price)
               .setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBookTicketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new PassengerHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SelectFlight().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookTicket;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFlights;
    // End of variables declaration//GEN-END:variables
}
